name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths: [".github/labels.yml"]
    branches: [main]

permissions:
  issues: write

jobs:
  sync:
    name: Sync repository labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
